version: "3.8"

services:
  frontend:
    build:
      context: ./nextjs-project
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Adjust port if needed

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Adjust port if needed
