import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/header/main-header";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div className="flex flex-col h-screen max-h-screen">
          <MainHeader />

          <div className="flex-grow ">{children}</div>
          <div className=" flex justify-center items-center space-x-6 mt-10 w-full">
            <Footer />
          </div>
        </div> */}

        <div className="flex flex-col ">
          <MainHeader />

          <main className="main-content ">{children}</main>

          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}
